### ISSUE TITLE
Archwiki

### ISSUE THREAD

**Issue by kiendang** [julie-is-late/aur-nvidia-container-toolkit#2]
Given the existence of multiple NVIDIA docker packages I thought it would be useful to have some kind of guides to avoid confusion so I added a section on NVIDIA docker on the `Docker` Archwiki page <https://wiki.archlinux.org/index.php/Docker#Run_GPU_accelerated_Docker_containers_with_NVIDIA_GPUs>. Would be nice if you could read through it to see if it's ok. Feel free to edit. Thanks!

**Comment by julie-is-late** [comment]
looks good. I made some super small edits but you already hit everything :)

**Comment by kiendang** [comment]
Thanks!
