### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by kiendang** [julie-is-late/aur-nvidia-container-toolkit#7]
Looks like there are new version for toolkit (1.1.1), runtime (3.2.0) and nvidia-docker (2.3.0). The new versions are available for Ubuntu etc but not made into a release on github. Could you ask the guy again? Thanks!

**Comment by kiendang** [comment]
Looks like they've made all the releases available. I've updated the packages but not pushed yet. Everything's straightforward except they moved nvidia-container-toolkit to a separate repo from runtime and use go module to build.

**Comment by julie-is-late** [comment]
awesome, thanks for taking care of this :)

yeah I gave this a once over yesterday and came to the same thoughts about it not seeming too complicated, and then it just gave me anxiety about wanting to redo the pkgbuilds from libnvidia-container haha... but stuff for another day.

everything looks good.

**Comment by kiendang** [comment]
yah good thing you didn't have to touch libnvidia-container this time lol. thanks for merging.

**Comment by julie-is-late** [comment]
want me to push everything out to the aur?

**Comment by kiendang** [comment]
that would be great. thanks!
